version: '3'

services:

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        container_name: appaltipop-es01
        environment:
            - discovery.type=single-node
            - cluster.name=appaltipop
        ports:
            - 9200:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:7.8.0
        container_name: appaltipop-kibana
        environment:
            SERVER_NAME: dashboard.appaltipop.it
            ELASTICSEARCH_HOSTS: http://es01:9200
        ports:
            - 5601:5601
